# Generated by Django 5.2.6 on 2025-10-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario411',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=15)),
                ('iban', models.CharField(max_length=34)),
                ('ejercicio', models.IntegerField()),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuota_tributaria', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_ingresar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cif', models.CharField(max_length=15)),
                ('territorio', models.CharField(default='No presencial', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
