# Generated by Django 5.2.7 on 2025-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impuesto_411', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario411',
            old_name='ejercicio',
            new_name='año',
        ),
        migrations.AlterField(
            model_name='formulario411',
            name='cuota_tributaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='formulario411',
            name='importe_ingresar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
